### ISSUE TITLE
Closing the last open tab with keyboard shortcut (cmd-w) causes error

### ISSUE THREAD

**Issue by efatsi** [olmokramer/atom-single-click-open#1]
Stacktrace:

```
TypeError: Cannot read property 'focus' of undefined
    at /Users/efatsi/.atom/packages/single-click-open/lib/single-click-open.js:56:33
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:560:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:617:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:692:35)
```

I can take a look into this later today to find a fix.

**Comment by olmokramer** [comment]
Thanks for catching this! Published v0.2.1 that solves this :)

**Comment by efatsi** [comment]
Sweet! Thanks for the useful and timely package!

**Comment by olmokramer** [comment]
You're welcome :) The double-clicking was just so annoying this just had to be done :angry:

**Comment by anseljh** [comment]
Thank you for this package! I was also completely befuddled by this weird double-click behavior, and looks like I'm not the only one: https://github.com/atom/atom/issues/11386

When did Atom add this??
