### ISSUE TITLE
Failed to activate the single-click-open package

### ISSUE THREAD

**Issue by bjmiller** [olmokramer/atom-single-click-open#3]
Started with Atom 1.12.0-beta0
Opening any document generates this error.

**Atom Version**: 1.12.0-beta0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [single-click-open](https://github.com/olmokramer/atom-single-click-open) package, v0.2.1
### Stack Trace

Failed to activate the single-click-open package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.activate (/Users/bmiller/.atom/packages/single-click-open/lib/single-click-open.js:28:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:783:28
```
###

**Comment by brettz9** [comment]
Not sure it is related, but I am getting this error and also a frozen Atom interface.

**Comment by brettz9** [comment]
Sorry, it is apparently not related as running `apm uninstall single-click-open` got rid of the error but not the frozen interface.

**Comment by swrobel** [comment]
I'm seeing this on 1.11.1 as well

**Comment by bjmiller** [comment]
I have an open PR for this, but it looks like @olmokramer hasn't had the chance to look at it yet.

You can, for now, copy the changes from #4 into your package locally.  Given how critically important this package is, I hope that the fix gets merged soon.

**Comment by panuhorsmalahti** [comment]
We really need this get merged.

**Comment by Scarysize** [comment]
@panuhorsmalahti Seems pretty abandoned to me 😞  Is someone open to maintaining a fork?

**Comment by bronson** [comment]
Failing for me on Atom 1.11.2.

**Comment by panuhorsmalahti** [comment]
@bjmiller could you publish your fork for the time being?

**Comment by NoahDavidATL** [comment]
Yep, the fix posted above works perfectly for me. Thanks so much, love this package.

**Comment by bjmiller** [comment]
I'd like to avoid forking the package.  Having two serves to confuse people who are looking for the answer to this issue.  I'd far rather see @olmokramer simply merge the fix.

**Comment by MiracleBlue** [comment]
If the fix doesn't get merged after another week (7 days), I'd say it's time to fork.  He appears to be active on his other repos on github, but has not responded to anyone on this one, which is a shame.  So if we cant get it merged after that time, then we need to either fork or make a whole new package.  I'd be happy to do it myself if you'd prefer, just let me know.  I can't survive in Atom without single click to open, and the error messages every time I update are getting annoying now ;)

**Comment by dohnutt** [comment]
Thanks for this fix... It's been bothering me for weeks now Would love to see this get merged in

**Comment by mdeggies** [comment]
Such a simple fix. Thanks!

**Comment by MiracleBlue** [comment]
@olmokramer was kind enough to give me contributor rights to the project, so I can now help keep things moving in his absence.  Latest version, 0.2.2, has been published with @bjmiller's patch for this issue.  Please give it a try and let me know how it goes, and feel free to post more issues and pull requests and I'll make sure to get to them in a reasonable time frame :)

**Comment by bjmiller** [comment]
Thank you for finding a way to get this done, and avert a very inconvenient fork.
